<?php

/**
 * Implements hook_theme().
 */
function angularjs_text_slider_theme($existing, $type, $theme, $path) {
  return array(
    'angularjs_text_slider_block' => array(
      'template' => 'angularjs-text-slider-block',
      'template' => 'angularjs-text-slider-block',
      'variables' => array()
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function angularjs_text_slider_block_info() {

  $blocks['angularjs_text_slider_block'] = array(
    'info' => t('AngularJS Text Slider'),
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function angularjs_text_slider_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'angularjs_text_slider_block':
      $block['subject'] = t('AngularJS Text slider');
      $block['content'] = array(
        '#theme' => 'angularjs_text_slider_block',
        '#attached' => array(
          'js' => array(
            drupal_get_path('module', 'angularjs_text_slider') . '/js/script.js',
          ),
          'css' => array(
            drupal_get_path('module', 'angularjs_text_slider') . '/css/style.css',
          ),
        ),
      );
    break;
  }

  return $block;
}

?>
